# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

ENV["MATCH_GIT_URL"] = "https://gitlab.com/Alireza12t/developer-profile"
ENV["FASTLANE_OUTPUT_DIRECTORY"] = "fastlane/output"
@output_directory = ENV["FASTLANE_OUTPUT_DIRECTORY"]
# git url of match
@match_git_url = ENV["MATCH_GIT_URL"]



default_platform(:ios)

platform :ios do


desc "TestFlight Test"
lane :beta do
match(git_url: @match_git_url,
type: "appstore",
app_identifier: "com.toghyiani.alireza.FMD",
readonly: false)

# increase build number everytime when packaging a new build
increment_build_number

build_app(scheme: "FMD")
 
upload_to_testflight(username: "alireza12.developer@gmail.com")

end 


end
